### ISSUE TITLE
How this is related to lrucache

### ISSUE THREAD

**Issue by phadej** [cocreature/lrucaching#1]
http://hackage.haskell.org/package/lrucache ?

**Comment by cocreature** [comment]
It is a completely separate package. `lrucache` contains a serious bug in `insertInforming` and the maintainer is not responding so I created my own package with a different API (and completely different code).

**Comment by phadej** [comment]
I'd put that into `README`.

**Comment by cocreature** [comment]
Done, thanks for noticing, I was planning to add that but forgot about it.

**Comment by agrafix** [comment]
I think now this package is the `lrucache` package on hackage?

**Comment by cocreature** [comment]
@agrafix I’m not sure what you’re saying here. What I said before still holds: This package is completely separate from the `lrucache` package on hackage and is called `lrucaching` (yes, I should have found a better name but that’s a different problem).

**Comment by agrafix** [comment]
Ah, sorry, okay i mixed it up with `lrucaching`...
