### ISSUE TITLE
Please support newer base-compat

### ISSUE THREAD

**Issue by iustin** [cocreature/lrucaching#8]
There's base-compat 0.13 for GHC 9.6, and 0.13.1 for GHC 9.8. Could you please test and release with increased upper bounds? See https://hackage.haskell.org/package/base-compat.

**Comment by iustin** [comment]
Note: I've tested a build for my app with forced ignore deps and the build succeeded, so I think there should be no (significant) issues with bumping the upper bound.

**Comment by cocreature** [comment]
I've uploaded 0.3.4 which includes this.

**Comment by iustin** [comment]
Thanks!
